on:
  push:
    branches: [ release/**, hotfix/** ]

name: Deploy "Dummy App" on Staging Environment

jobs:
  deploy:
    name: Deploy "Dummy App"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get Package Version
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

    - name: Build, tag, and push image Dummy App to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPOSITORY }}
        IMAGE_TAG: v.${{ env.PACKAGE_VERSION }}-staging-${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f cicd/docker/Dockerfile --build-arg REPO_PROTO=$REPO_PROTO
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image-name::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Change Deployment Image Dummy App on EKS
      uses: ianbelcher/eks-kubectl-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        cluster_name: ${{ secrets.CLUSTER_NAME_NON_PRODUCTION }}
        args: set image --record deployment/${{ secrets.CONTAINER_NAME }}-http-staging ${{ secrets.CONTAINER_NAME }}-http-staging=${{ steps.build-image.outputs.image-name }} -n ${{ secrets.NAMESPACE_STAGING }}
